LOC_WORKSPACE_LOGIN_IPT_USERNAME = "xpath://input[@id='username']"
LOC_WORKSPACE_LOGIN_IPT_PASSWORD = "xpath://input[@id='password']"
LOC_WORKSPACE_LOGIN_AGENT = "xpath://*[contains(text(), 'Login Agent')]"
LOC_WORKSPACE_LOGIN_AVATAR = "xpath://img[@class='agent-avatar']"
LOC_WORKSPACE_LOGIN_BTN_SIGNIN = "login-button"
LOC_WORKSPACE_LOGIN_BTN_ACTIVATE = "xpath://button[@puppeteer-id='activate--button']"
LOC_WORKSPACE_LOGIN_LABEL_AGENT = "xpath://h1[@class='md-title']"
LOC_WORKSPACE_LOGIN_BTN_STARTWORK = "xpath://button[@puppeteer-id='start-work--button']"
LOC_WORKSPACE_LOGOUT = "xpath://button[contains(@id, 'login-button') or contains(@id, 'ow_activate')]"
LOC_WORKSPACE_HOME_DROPDOWN_MENU = "xpath://button[@puppeteer-id='agent--dropdown-button']"
LOC_WORKSPACE_HOME_MENU_HEADER = "xpath://div[@class='menu-header__data']"
#LOC_WORKSPACE_HOME_DROPDOWN_READY = "xpath://button[@puppeteer-id='go-ready--dropdown-button']"
#   ======  ERROR MESSAGE  ======
LOC_WORKSPACE_ERROR_HEADER = "xpath://div[@class='error-header']"
LOC_WORKSPACE_ERROR_BODY = "xpath://div[@class='error-body']"