url_power = 'https://vietlott.vn/vi/trung-thuong/ket-qua-trung-thuong/so-ket-qua?gameid=4&nocatche=1'
url_mega = 'https://vietlott.vn/vi/trung-thuong/ket-qua-trung-thuong/so-ket-qua?gameid=3&nocatche=1'
implicitly_wait = 60
set_page_load_timeout = 120
csv_filename_power = "csv/power_test3.csv"
csv_filename_mega = "csv/mega_test4.csv"
csv_data_dict = {}
csv_data_list = []
start_page = 0
