WORKCARD_ID_VAR = "${WORKCARD_ID}"
# CONTACT_TYPE = "${CONTACT_TYPE}"
# LOC_CUSTOMER_JOURNEY_TOUCHPOINT = "xpath://div[@class='journey-container']//*[contains(text(),'" + CONTACT_TYPE +"')]"
LOC_CUSTOMER_JOURNEY_TOUCHPOINT1 = "xpath://div[@class='journey-container']//*[contains(text(),'{}')]"
LOC_CUSTOMER_JOURNEY_TOUCHPOINT = "xpath://div[@interaction-id='" + WORKCARD_ID_VAR +"']//div[@class='journey-container']//*[contains(text(),{})]"
LOC_CUSTOMER_JOURNEY_TOUCHPOINT_LABEL = "xpath://*[@class='{}']"

LOC_CUSTOMER_JOURNEY_TRANSCRIPT = "xpath://div[@interaction-id='" + WORKCARD_ID_VAR +"']//div[@id='transcriptButton']"
LOC_CUSTOMER_JOURNEY_TRANSCRIPT_BTN = "xpath://div[@id='transcriptButton']"
LOC_CUSTOMER_JOURNEY_TRANSCRIPT_CHAT = "xpath://div[@class='journey-transcript-content']"
LOC_CUSTOMER_JOURNEY_TRANSCRIPT_EMAIL = "xpath://p[@class='email-body-content']"
LOC_CUSTOMER_JOURNEY_TRANSCRIPT_ATTACHMENT = "xpath://div[@class='uploaded-attachment_name flexAuto']"
LOC_CUSTOMER_JOURNEY_TRANSCRIPT_CONTENT = "xpath://div[@class='modal-content ui-draggable']"
LOC_CUSTOMER_JOURNEY_TRANSCRIPT_CLOSE_BTN = "xpath://button[@class='modal-footer-closeButton']"

LOC_CUSTOMER_JOURNEY_GET_CUSTOMER_ID = "xpath://div[@interaction-id='" + WORKCARD_ID_VAR +"']//div[@ng-if='isIntrinsicPopulated']//table//tr[6]//td[2]"
# LOC_CUSTOMER_JOURNEY_GET_CUSTOMER_ID = "xpath://div[@ng-if='isIntrinsicPopulated']//table//tr[6]//td[2]"
LOC_CUSTOMER_JOURNEY_GET_CONTACT_TIME = "xpath://div[@class='widget__content--indented ps ps--active-y']//table//tr[8]//td[2]"
LOC_CUSTOMER_JOURNEY_TOOLTIP_TOUCHPOINT = "xpath://div[@class='journey-tooltip']"
LOC_CUSTOMER_JOURNEY_TOOLTIP_STATUS = "xpath://div[@class='summaryRow']"
LOC_CUSTOMER_JOURNEY_TOOLTIP_TIMELINE = "xpath://div[@interaction-id='" + WORKCARD_ID_VAR +"']//div[@id='cd-timeline']"
# LOC_CUSTOMER_JOURNEY_TOOLTIP_TIMELINE = "xpath://div[@id='cd-timeline']"
LOC_CUSTOMER_JOURNEY_TIME_RANGE_SELECTION = "xpath://select[@title='Time Range selection']"
LOC_CUSTOMER_JOURNEY_TIME_RANGE_OPTION = "xpath://select[@title='Time Range selection']//*[contains(text(),'{}')]"
LOC_CUSTOMER_JOURNEY_REFETCH_BTN = "xpath://button[@aria-label='Re-fetch Journey']"
